#!/bin/bash
## Variables
hcrprDir="$HOME/MEGA/backups/db/hcrpr"

## Methods

create_hcrpr_db_backups_directory() {
  echo "> Criando o diretório '$hcrprDir'..."
  mkdir -p $hcrprDir
} 

dump_database () {
  echo "> Realizando o dump do banco de dados..."
  mysqldump -u root -h 127.0.0.1 -P 3306 --password='password' hcrpr > $hcrprDir/hcrpr-$(date +%d%m%Y).sql
  echo "> Dump realizado..."
}

has_file_older_than () {
  days=$1
  if (($(find ./ -mtime +$days | wc -l) > 0)); then
    echo 0
  else
    echo 1
  fi
}

delete_files_older_than() {
  echo "> Verificando se há harquivos para remover..."
  cd $hcrprDir
  echo "> Pasta atual:" $(pwd)

  days=$1  
  if (( $days < 0)); then
    echo "> O dia informádo é inválido..."
    return
  fi
  if [[ $(has_file_older_than $days) == 1 ]]; then
    echo "> Não há arquivos para remover..."
    return
  fi
  
  echo "> Removendo arquivos com mais de $days dias..."
  rm $(find ./ -mtime +$days)
}

goodbye() {
  echo "> Tchau :)"
}

## Code execution

if [ ! -d "$hcrprDir" ]; then
  create_hcrpr_db_backups_directory
fi

dump_database

delete_files_older_than 30

goodbye
