#!/bin/bash
## Variables
backupsDir="$HOME/MEGA/backups"
dbBackupsDir="$backupsDir/db/"
hcrprDir="$dbBackupsDir/hcrpr"

## Methods
create_backups_directory() {
  echo "Creating directory '$backupsDir'..."
  mkdir $backupsDir
}

create_db_backups_directory () {
  echo "Creating directory '$dbBackupsDir'..."
  mkdir $dbBackupsDir
}

create_hcrpr_directory() {
  echo "Creating directory '$hcrprDir'..."
  mkdir $hcrprDir
} 

dump_database () {
  echo "Realizando o dump do banco de dados..."
  mysqldump -u root -h 127.0.0.1 -P 3306 --password='password' hcrpr > $hcrprDir/hcrpr-$(date +%d%m%Y).sql
  echo "Dump realizado..."
}

has_file_older_than () {
  days=$1
  if (($(find ./ -mtime +$days | wc -l) > 0)); then
    echo 0
  else
    echo 1
  fi
}

delete_files_older_than() {
  echo "Verificando se há harquivos para remover..."
  cd $hcrprDir
  echo ">> Pasta atual:" $(pwd)

  days=$1  
  if (( $days < 0)); then
    echo "O dia informádo é inválido..."
    return
  fi
  if [[ $(has_file_older_than $days) == 1 ]]; then
    echo "Não há arquivos para remover..."
    return
  fi
  
  echo "Removendo arquivos com mais de $days dias..."
  rm $(find ./ -mtime +$days)
}

## Code execution
if [ ! -d $backupsDir ]; then
  create_backups_directory
fi 

if [ ! -d "$dbBackupsDir" ]; then
  create_db_backups_directory
fi

if [ ! -d "$hcrprDir" ]; then
  create_hcrpr_directory
fi

dump_database

delete_files_older_than 30
